# Generated by Django 5.2 on 2026-05-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0006_alter_companybottcrun_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botruntestcasemap',
            name='metric_name',
            field=models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS'), ('geval', 'GEVAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalbotruntestcasemap',
            name='metric_name',
            field=models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS'), ('geval', 'GEVAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tcbotrunmetrics',
            name='metric_name',
            field=models.CharField(choices=[('answer_relevancy', 'ANSWER_RELEVANCY'), ('faithfullness', 'FAITHFULLNESS'), ('contextual_precision', 'CONTEXTUAL_PRECISION'), ('contextual_recall', 'CONTEXTUAL_RECALL'), ('contextual_relevancy', 'CONTEXTUAL_RELEVANCY'), ('bias', 'BIAS'), ('toxicity', 'TOXICITY'), ('summarization', 'SUMMARIZATION'), ('prompt_allignment', 'PROMPT_ALLIGNMENT'), ('hallucination', 'HALLUCINATION'), ('json_correctness', 'JSON_CORRECTNESS'), ('geval', 'GEVAL')], max_length=100),
        ),
    ]
