# Generated by Django 5.2 on 2026-06-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0008_alter_companybottcrun_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybottcrun',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('openrouter', 'Openrouter')], default='openai', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybottcrun',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('openrouter', 'Openrouter')], default='openai', max_length=100),
        ),
    ]
