# Generated by Django 5.1.2 on 2024-11-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_companybot_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(max_length=1000, upload_to='uploads/'),
        ),
    ]
