# Generated by Django 5.2 on 2026-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0082_companybot_use_vector_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI'), ('claude-3-haiku-20240307', 'Claude 3 Haiku'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('claude-3-7-sonnet-20250219', 'Claude 3.7 Sonnet'), ('claude-haiku-4-5', 'Claude Haiku 4.5'), ('claude-sonnet-4-5', 'Claude Sonnet 4.5'), ('claude-opus-4-5', 'Claude Opus 4.5')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC')], default='bedrock', help_text='Select the LLM provider (BEDROCK, ANTHROPIC, or OPENAI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4', 'GPT4'), ('gpt-4.1', 'GPT4_1'), ('gpt-4.1-mini', 'GPT4_1-MINI'), ('gpt-4-1106-preview', 'GPT4-128k'), ('gpt-4-turbo', 'GPT4_TURBO'), ('llama3-8b-8192', 'LLAMA_3_8B_8192'), ('llama3-70b-8192', 'LLAMA_3_70B_8192'), ('llama-3.1-70b-versatile', 'LLAMA_3_1_70B_VERSATILE'), ('llama-3.1-8b-instant', 'LLAMA_3_1_8B_INSTANT'), ('meta.llama3-1-70b-instruct-v1:0', 'LLAMA_3_1_70B_INSTRUCT'), ('meta.llama3-1-8b-instruct-v1:0', 'LLAMA_3_1_8B_INSTRUCT'), ('us.meta.llama3-3-70b-instruct-v1:0', 'LLAMA_3_3_70B_INSTRUCT'), ('us.meta.llama3-3-8b-instruct-v1:0', 'LLAMA_3_3_8B_INSTRUCT'), ('mixtral-8x7b-32768', 'MIXTRAL_8X70B_32768'), ('gpt-4o', 'GPT4_O'), ('gpt-4o-mini', 'GPT4_O_MINI'), ('meta-llama/Meta-Llama-3.1-8B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct'), ('gpt-5.2', 'GPT_5_2'), ('gpt-5.2-pro', 'GPT_5_2_PRO'), ('gpt-5-mini', 'GPT_5_MINI'), ('claude-3-haiku-20240307', 'Claude 3 Haiku'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet'), ('claude-3-opus-20240229', 'Claude 3 Opus'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('claude-3-7-sonnet-20250219', 'Claude 3.7 Sonnet'), ('claude-haiku-4-5', 'Claude Haiku 4.5'), ('claude-sonnet-4-5', 'Claude Sonnet 4.5'), ('claude-opus-4-5', 'Claude Opus 4.5')], default='gpt-4o-mini', help_text='Select the LLM model to be used by the bot (e.g., GPT-4o, GPT-4).', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC')], default='bedrock', help_text='Select the LLM provider (BEDROCK, ANTHROPIC, or OPENAI)', max_length=100),
        ),
    ]
