# Generated by Django 5.2 on 2026-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0083_alter_companybot_llm_model_alter_companybot_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='enable_web_search',
            field=models.BooleanField(default=False, help_text='Enable web search via the LLM gateway.'),
        ),
        migrations.AddField(
            model_name='companybot',
            name='web_search_context_size',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Amount of context the web search retrieves. Only used when enable_web_search is True.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='enable_web_search',
            field=models.BooleanField(default=False, help_text='Enable web search via the LLM gateway.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='web_search_context_size',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Amount of context the web search retrieves. Only used when enable_web_search is True.', max_length=10),
        ),
    ]
