# Generated by Django 5.2 on 2026-06-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0084_companybot_enable_web_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='title_bot',
            field=models.ForeignKey(blank=True, help_text='Optional bot for session title generation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_flows', to='chatbot.companybot'),
        ),
        migrations.AddField(
            model_name='historicalflow',
            name='title_bot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional bot for session title generation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.companybot'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/heif', 'HEIF'), ('image/heic', 'HEIC'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('application/pdf', 'PDF'), ('text/plain', 'TXT'), ('text/csv', 'CSV'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/svg+xml', 'SVG'), ('image/webp', 'WEBP'), ('image/heif', 'HEIF'), ('image/heic', 'HEIC'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX')], max_length=100, null=True),
        ),
    ]
