# Generated by Django 5.2 on 2026-06-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0085_flow_title_bot_historicalflow_title_bot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('openrouter', 'Openrouter')], default='bedrock', help_text='Select the LLM provider (BEDROCK, ANTHROPIC, or OPENAI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='provider',
            field=models.CharField(choices=[('bedrock', 'BEDROCK'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('openrouter', 'Openrouter')], default='bedrock', help_text='Select the LLM provider (BEDROCK, ANTHROPIC, or OPENAI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='userid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['userid'], name='chatbot_pro_userid_3d404e_idx'),
        ),
    ]
