# Generated by Django 5.2 on 2026-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0086_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='chatbot_pro_userid_3d404e_idx',
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('userid__isnull', False)), fields=('userid',), name='uniq_profile_userid'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('userid__isnull', True)), fields=('email', 'company_id'), name='uniq_profile_email_company'),
        ),
    ]
