# Generated by Django 5.2 on 2026-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0087_remove_profile_chatbot_pro_userid_3d404e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='botvernacular',
            name='bot_vernacu_company_483975_idx',
        ),
        migrations.AddConstraint(
            model_name='botvernacular',
            constraint=models.UniqueConstraint(fields=('company_bot', 'language'), name='uniq_bot_vernacular_bot_language'),
        ),
    ]
