# Generated by Django 5.2 on 2026-07-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0088_remove_botvernacular_bot_vernacu_company_483975_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], default='en', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('te', 'Telugu'), ('or', 'Odia'), ('ta', 'Tamil')], max_length=10),
        ),
        migrations.CreateModel(
            name='CompanyChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up', models.BooleanField(default=False, help_text='True if the user gave a positive rating in this submission.')),
                ('thumbs_down', models.BooleanField(default=False, help_text='True if the user gave a negative rating in this submission. Cannot be True at the same time as thumbs_up (enforced in the serializer).')),
                ('comment', models.TextField(blank=True, help_text='Optional free-text feedback typed by the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feedback was submitted. Immutable — also used to determine the current state (latest row wins) and submission order.')),
                ('company_chat', models.ForeignKey(help_text='The bot response (CompanyChat row) this feedback is about.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.companychat')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_chat', '-created_at'], name='chatbot_com_company_f623f2_idx')],
            },
        ),
    ]
