# Generated by Django 5.2 on 2026-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0089_alter_chatsession_language_alter_story_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='gateway_model',
            field=models.CharField(blank=True, help_text='Select the model for the chosen provider. If you just changed the provider, save the bot first — the model list here updates to match the new provider after saving.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companybot',
            name='gateway_provider',
            field=models.CharField(blank=True, help_text='Select the LLM provider to use. Choices are fetched live from the LLM gateway.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companybot',
            name='gateway_sub_provider',
            field=models.CharField(blank=True, help_text="Only used when the gateway provider is 'openrouter'. Select which upstream endpoint (e.g. DeepInfra, Google, Anthropic) should serve the chosen model. If you just changed the model, save the bot first — the choices here update to match after saving. Stored value is the endpoint's routable tag, not just the provider display name.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='gateway_model',
            field=models.CharField(blank=True, help_text='Select the model for the chosen provider. If you just changed the provider, save the bot first — the model list here updates to match the new provider after saving.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='gateway_provider',
            field=models.CharField(blank=True, help_text='Select the LLM provider to use. Choices are fetched live from the LLM gateway.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='gateway_sub_provider',
            field=models.CharField(blank=True, help_text="Only used when the gateway provider is 'openrouter'. Select which upstream endpoint (e.g. DeepInfra, Google, Anthropic) should serve the chosen model. If you just changed the model, save the bot first — the choices here update to match after saving. Stored value is the endpoint's routable tag, not just the provider display name.", max_length=100, null=True),
        ),
    ]
