# Generated by Django 5.2 on 2026-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0090_add_companybot_gateway_provider_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybot',
            name='cache_targets',
            field=models.JSONField(blank=True, help_text="List of request parts to cache (e.g. ['prompt', 'tools']). Choices are fetched live from the LLM gateway. Required when Enable Cache is checked.", null=True),
        ),
        migrations.AddField(
            model_name='companybot',
            name='cache_ttl',
            field=models.CharField(blank=True, help_text='TTL to use for cached content. Choices are fetched live from the LLM gateway. Required when Enable Cache is checked.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companybot',
            name='enable_cache',
            field=models.BooleanField(default=False, help_text='Enable prompt/tool caching via the LLM gateway. When enabled, Cache TTL and Cache Targets become required.'),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='cache_targets',
            field=models.JSONField(blank=True, help_text="List of request parts to cache (e.g. ['prompt', 'tools']). Choices are fetched live from the LLM gateway. Required when Enable Cache is checked.", null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='cache_ttl',
            field=models.CharField(blank=True, help_text='TTL to use for cached content. Choices are fetched live from the LLM gateway. Required when Enable Cache is checked.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanybot',
            name='enable_cache',
            field=models.BooleanField(default=False, help_text='Enable prompt/tool caching via the LLM gateway. When enabled, Cache TTL and Cache Targets become required.'),
        ),
    ]
