# Generated by Django 5.2 on 2026-08-27 08:55

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0091_companybot_cache_targets_companybot_cache_ttl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voice',
            options={'base_manager_name': 'all_voices', 'default_manager_name': 'all_voices'},
        ),
        migrations.AlterModelManagers(
            name='voice',
            managers=[
                ('all_voices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='historicalvoice',
            name='is_fallback',
            field=models.BooleanField(default=False, editable=False, help_text='Auto-derived from primary_voice — True for a row that is a fallback config.'),
        ),
        migrations.AddField(
            model_name='historicalvoice',
            name='primary_voice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Set only on a row that is a fallback config for a Text To Text primary row.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.voice'),
        ),
        migrations.AddField(
            model_name='voice',
            name='is_fallback',
            field=models.BooleanField(default=False, editable=False, help_text='Auto-derived from primary_voice — True for a row that is a fallback config.'),
        ),
        migrations.AddField(
            model_name='voice',
            name='primary_voice',
            field=models.OneToOneField(blank=True, help_text='Set only on a row that is a fallback config for a Text To Text primary row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallback_config', to='chatbot.voice'),
        ),
    ]
