# Generated by Django 5.2 on 2026-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0092_add_voice_fallback_provider'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_fallback', False)), fields=('company_bot', 'type', 'language'), name='unique_primary_voice_per_bot_type_language'),
        ),
    ]
