# Generated by Django 5.2 on 2026-08-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0093_voice_unique_primary_per_type_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybot',
            name='tool_context',
            field=models.TextField(blank=True, help_text='JSON tool definitions for the LLM. For SIMPLE bots, the search_knowledge_base entry here is auto-added/removed based on Use vector service.', null=True),
        ),
        migrations.AlterField(
            model_name='companybot',
            name='use_vector_service',
            field=models.BooleanField(default=False, help_text='Enable vector knowledge base search. Uses a two-step LLM call: first to extract the search query, then to answer with retrieved context. SIMPLE bots only: on save, this adds/removes the search_knowledge_base tool in Tool context automatically, leaving other tools untouched.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='tool_context',
            field=models.TextField(blank=True, help_text='JSON tool definitions for the LLM. For SIMPLE bots, the search_knowledge_base entry here is auto-added/removed based on Use vector service.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanybot',
            name='use_vector_service',
            field=models.BooleanField(default=False, help_text='Enable vector knowledge base search. Uses a two-step LLM call: first to extract the search query, then to answer with retrieved context. SIMPLE bots only: on save, this adds/removes the search_knowledge_base tool in Tool context automatically, leaving other tools untouched.'),
        ),
    ]
