# Generated by Django 5.2 on 2026-09-01 09:30

import logging

import django.db.models.deletion
import pycountry
import simple_history.models
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger('django')

# Mirrors chatbot/constants/provider_slugs.py — kept as a local literal since
# data migrations should stay self-contained and not depend on app code that
# may change shape later.
SEED_PROVIDERS = [
    ("Google", "google"),
    ("AI4Bharat", "ai4bharat"),
    ("OpenAI Whisper", "openai-whisper"),
    ("Sarvam", "sarvam"),
    ("Custom LLM", "custom-llm"),
]
VOICE_PROVIDER_TO_SLUG = dict(zip(
    ("GOOGLE", "AI4Bharat", "OPENAI_WHISPER", "Sarvam", "CUSTOM_LLM"),
    (slug for _, slug in SEED_PROVIDERS),
))


def seed_providers(apps, schema_editor):
    Provider = apps.get_model('chatbot', 'Provider')
    for name, slug in SEED_PROVIDERS:
        Provider.objects.get_or_create(slug=slug, defaults={'name': name})


def _resolve_language(Language, code):
    code = code or "unknown"
    existing = Language.objects.filter(iso_code=code).first()
    if existing:
        return existing

    pycountry_language = pycountry.languages.get(alpha_2=code) or pycountry.languages.get(alpha_3=code)
    if pycountry_language:
        return Language.objects.create(iso_code=code, name=pycountry_language.name)

    logger.warning("Voice backfill: %r is not a known ISO 639 code — creating a best-effort Language row.", code)
    return Language.objects.create(iso_code=code, name=code)


def backfill_voice_language_provider(apps, schema_editor):
    Voice = apps.get_model('chatbot', 'Voice')
    Language = apps.get_model('chatbot', 'Language')
    Provider = apps.get_model('chatbot', 'Provider')
    # Voice declares custom managers (objects/all_voices) that aren't migrations-aware
    # (no use_in_migrations = True), so the historical model here has no `.objects` —
    # use the always-present unfiltered default manager instead.
    all_voices = Voice._default_manager

    language_cache = {}
    provider_cache = {}

    pairs = all_voices.values_list('language', 'provider').distinct()
    for language_code, provider_value in pairs:
        if language_code not in language_cache:
            language_cache[language_code] = _resolve_language(Language, language_code)
        language_row = language_cache[language_code]

        if provider_value not in provider_cache:
            slug = VOICE_PROVIDER_TO_SLUG.get(provider_value)
            provider_cache[provider_value] = Provider.objects.filter(slug=slug).first() if slug else None
        provider_row = provider_cache[provider_value]

        if not provider_row:
            logger.warning(
                "Voice backfill: no seeded Provider for legacy provider value %r — %d row(s) with "
                "language=%r left with provider_ref unset.",
                provider_value, all_voices.filter(language=language_code, provider=provider_value).count(),
                language_code,
            )
            all_voices.filter(language=language_code, provider=provider_value).update(language_ref=language_row)
            continue

        all_voices.filter(language=language_code, provider=provider_value).update(
            language_ref=language_row, provider_ref=provider_row,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0094_alter_companybot_tool_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name. Must match a key in chatbot/constants/provider_dispatch.py for TTS/STT/translate calls to actually work for this provider.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='language',
            field=models.CharField(blank=True, help_text='Legacy — frozen, hidden from admin, auto-synced from language_ref on save(). Kept only for backward compatibility with existing read call sites.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvoice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', help_text='Legacy — frozen, hidden from admin, auto-synced from provider_ref on save(). Kept only for backward compatibility with existing read call sites.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='language',
            field=models.CharField(blank=True, help_text='Legacy — frozen, hidden from admin, auto-synced from language_ref on save(). Kept only for backward compatibility with existing read call sites.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('AI4Bharat', 'AI4Bharat'), ('OPENAI_WHISPER', 'OpenAI Whisper'), ('Sarvam', 'Sarvam'), ('CUSTOM_LLM', 'Custom LLM')], default='AI4Bharat', help_text='Legacy — frozen, hidden from admin, auto-synced from provider_ref on save(). Kept only for backward compatibility with existing read call sites.', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLanguage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('iso_code', models.CharField(db_index=True, help_text='ISO 639 code, selected from the pycountry library dropdown (admin-form validated).', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical language',
                'verbose_name_plural': 'historical languages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name. Must match a key in chatbot/constants/provider_dispatch.py for TTS/STT/translate calls to actually work for this provider.', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical provider',
                'verbose_name_plural': 'historical providers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='ISO 639 code, selected from the pycountry library dropdown (admin-form validated).', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['iso_code'], name='chatbot_lan_iso_cod_f0ffa0_idx')],
            },
        ),
        migrations.AddField(
            model_name='historicalvoice',
            name='language_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Structured language for this voice config.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.language'),
        ),
        migrations.AddField(
            model_name='voice',
            name='language_ref',
            field=models.ForeignKey(blank=True, help_text='Structured language for this voice config.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voices', to='chatbot.language'),
        ),
        migrations.CreateModel(
            name='HistoricalLanguageProviderConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('custom_code', models.CharField(blank=True, default='', help_text="Overrides the language's iso_code for this provider's outbound API calls. Leave blank to use iso_code as-is.", max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.language')),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.provider')),
            ],
            options={
                'verbose_name': 'historical language provider config',
                'verbose_name_plural': 'historical language provider configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalvoice',
            name='provider_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Structured provider for this voice config.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.provider'),
        ),
        migrations.AddField(
            model_name='voice',
            name='provider_ref',
            field=models.ForeignKey(blank=True, help_text='Structured provider for this voice config.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voices', to='chatbot.provider'),
        ),
        migrations.CreateModel(
            name='LanguageProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', models.CharField(blank=True, default='', help_text="Overrides the language's iso_code for this provider's outbound API calls. Leave blank to use iso_code as-is.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='chatbot.language')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_configs', to='chatbot.provider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'provider'), name='unique_language_provider')],
            },
        ),
        # Seed the 5 providers the dispatch registry (chatbot/constants/provider_dispatch.py)
        # already knows how to call, then backfill every existing Voice row's new FKs from its
        # legacy language/provider strings — both must run before language_ref/provider_ref are
        # tightened to NOT NULL below.
        migrations.RunPython(seed_providers, migrations.RunPython.noop),
        migrations.RunPython(backfill_voice_language_provider, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='voice',
            name='language_ref',
            field=models.ForeignKey(
                help_text='Structured language for this voice config.',
                on_delete=django.db.models.deletion.PROTECT, related_name='voices', to='chatbot.language',
            ),
        ),
        migrations.AlterField(
            model_name='voice',
            name='provider_ref',
            field=models.ForeignKey(
                help_text='Structured provider for this voice config.',
                on_delete=django.db.models.deletion.PROTECT, related_name='voices', to='chatbot.provider',
            ),
        ),
    ]
