# Generated by Django 5.2 on 2026-09-02 06:51

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger('django')


def backfill_bot_vernacular_language_ref(apps, schema_editor):
    """Lookup-only backfill (no Language rows created) — language_ref is a purely
    derived convenience field, not load-bearing, so leaving it null for a code with
    no matching Language row is fine (matches BotVernacular.save()'s own logic)."""
    BotVernacular = apps.get_model('chatbot', 'BotVernacular')
    Language = apps.get_model('chatbot', 'Language')

    language_cache = {}
    codes = BotVernacular.objects.values_list('language', flat=True).distinct()
    for code in codes:
        if code not in language_cache:
            language_cache[code] = Language.objects.filter(iso_code=code).first()
        language_row = language_cache[code]
        if language_row:
            BotVernacular.objects.filter(language=code).update(language_ref=language_row)
        else:
            logger.warning(
                "BotVernacular backfill: no Language row for iso_code=%r — left language_ref null.", code,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0099_drop_shikshalokam_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='botvernacular',
            name='language_ref',
            field=models.ForeignKey(blank=True, editable=False, help_text='Structured language, auto-derived from `language` on save(). Not load-bearing — purely a derived convenience field; `language` remains the source of truth.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_vernaculars', to='chatbot.language'),
        ),
        migrations.AddField(
            model_name='historicalbotvernacular',
            name='language_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Structured language, auto-derived from `language` on save(). Not load-bearing — purely a derived convenience field; `language` remains the source of truth.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.language'),
        ),
        migrations.RunPython(backfill_bot_vernacular_language_ref, migrations.RunPython.noop),
    ]
