# Generated by Django 5.2 on 2026-09-02 06:58

import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger('django')


def backfill_chatsession_language_ref(apps, schema_editor):
    """Lookup-only backfill (no Language rows created) — language_ref is a purely
    derived convenience field, not load-bearing, so leaving it null for a code with
    no matching Language row is fine (matches ChatSession.save()'s own logic)."""
    ChatSession = apps.get_model('chatbot', 'ChatSession')
    Language = apps.get_model('chatbot', 'Language')

    language_cache = {}
    codes = ChatSession.objects.values_list('language', flat=True).distinct()
    for code in codes:
        if code not in language_cache:
            language_cache[code] = Language.objects.filter(iso_code=code).first()
        language_row = language_cache[code]
        if language_row:
            ChatSession.objects.filter(language=code).update(language_ref=language_row)
        else:
            logger.warning(
                "ChatSession backfill: no Language row for iso_code=%r — left language_ref null.", code,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0100_bot_vernacular_language_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language_ref',
            field=models.ForeignKey(blank=True, editable=False, help_text='Structured language, auto-derived from `language` on save(). Not load-bearing — purely a derived convenience field; `language` remains the source of truth.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='chatbot.language'),
        ),
        migrations.RunPython(backfill_chatsession_language_ref, migrations.RunPython.noop),
    ]
