# Generated by Django 5.2 on 2026-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0102_seed_chatsession_bot_vernacular_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='en', help_text='Language code — controlled at the admin form layer via a Language-table-sourced dropdown (ChatSessionAdminForm), not by a fixed model-level choice list.', max_length=1000),
        ),
    ]
