# Generated by Django 5.2 on 2026-09-02 09:12

import logging

import chatbot.models.company_models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger('django')


def backfill_media_template_from_pdf_templates(apps, schema_editor):
    """Copy every existing PDFTemplates row into a new MediaTemplate(type=PDF, ...)
    row, so `MediaTemplate` becomes a complete source of truth without breaking
    flows already relying on their PDFTemplates row. get_or_create on
    template_name for idempotency (safe to re-run)."""
    PDFTemplates = apps.get_model('chatbot', 'PDFTemplates')
    MediaTemplate = apps.get_model('chatbot', 'MediaTemplate')

    for pdf_template in PDFTemplates.objects.all():
        _, created = MediaTemplate.objects.get_or_create(
            template_name=pdf_template.template_name,
            defaults={
                'type': 'PDF',
                'flow_id': pdf_template.flow_id,
                'constants_json': pdf_template.constants_json,
                'template': pdf_template.template,
            },
        )
        if not created:
            logger.info(
                "MediaTemplate backfill: %r already exists, skipping (re-run?)",
                pdf_template.template_name,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0103_chatsession_language_remove_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMediaTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], help_text='Output format this template produces.', max_length=10)),
                ('template_name', models.CharField(db_index=True, help_text='Unique name identifier for this template.', max_length=255)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('template', models.TextField(blank=True, help_text='Template content (HTML/Jinja2) - used when type=PDF.', null=True)),
                ('template_file', models.TextField(blank=True, help_text='Uploaded .docx template (Jinja2 tags via docxtpl) - used when type=DOCX.', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('flow', models.ForeignKey(blank=True, db_constraint=False, help_text='Flow associated with this template.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.flow')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Media Template',
                'verbose_name_plural': 'historical Media Templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], help_text='Output format this template produces.', max_length=10)),
                ('template_name', models.CharField(help_text='Unique name identifier for this template.', max_length=255, unique=True)),
                ('constants_json', models.JSONField(blank=True, help_text='JSON object containing constants/variables used in the template.', null=True)),
                ('template', models.TextField(blank=True, help_text='Template content (HTML/Jinja2) - used when type=PDF.', null=True)),
                ('template_file', models.FileField(blank=True, help_text='Uploaded .docx template (Jinja2 tags via docxtpl) - used when type=DOCX.', max_length=1000, null=True, upload_to=chatbot.models.company_models.get_media_template_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(blank=True, help_text='Flow associated with this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_templates', to='chatbot.flow')),
            ],
            options={
                'verbose_name': 'Media Template',
                'verbose_name_plural': 'Media Templates',
                'indexes': [models.Index(fields=['template_name'], name='chatbot_med_templat_5d19f1_idx'), models.Index(fields=['type'], name='chatbot_med_type_adbfd8_idx')],
            },
        ),
        migrations.RunPython(backfill_media_template_from_pdf_templates, migrations.RunPython.noop),
    ]
